version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: every-cup-shop
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
    networks:
      - app-staging-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-staging-data:/data
    networks:
      - app-staging-network
  
  app:
    image: "purps/every-cup-shop:v3"
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - app-staging-network

networks:
  app-staging-network:
    driver: bridge

volumes: 
  postgres-staging-data:
  redis-staging-data: